/*!Peripheral access API for STM32C031 microcontrollers (generated using svd2rust v0.37.1 (773caae 2025-10-19))

You can find an overview of the generated API [here].

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.

[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased
[repository]: https://github.com/rust-embedded/svd2rust*/
///Number available in the NVIC for configuring priority
pub const NVIC_PRIO_BITS: u8 = 2;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[cfg(feature = "rt")]
extern "C" {
    fn WWDG();
    fn PVM();
    fn RTC();
    fn FLASH();
    fn RCC();
    fn EXTI0_1();
    fn EXTI2_3();
    fn EXTI4_15();
    fn DMA1_CHANNEL1();
    fn DMA1_CHANNEL2_3();
    fn DMAMUX_DMA1_CHANNEL4_5();
    fn ADC();
    fn TIM1_BRK_UP_TRG_COM();
    fn TIM1_CC();
    fn TIM3();
    fn TIM14();
    fn TIM16();
    fn TIM17();
    fn I2C();
    fn SPI();
    fn USART1();
    fn USART2();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 29] = [
    Vector { _handler: WWDG },
    Vector { _handler: PVM },
    Vector { _handler: RTC },
    Vector { _handler: FLASH },
    Vector { _handler: RCC },
    Vector { _handler: EXTI0_1 },
    Vector { _handler: EXTI2_3 },
    Vector { _handler: EXTI4_15 },
    Vector { _reserved: 0 },
    Vector {
        _handler: DMA1_CHANNEL1,
    },
    Vector {
        _handler: DMA1_CHANNEL2_3,
    },
    Vector {
        _handler: DMAMUX_DMA1_CHANNEL4_5,
    },
    Vector { _handler: ADC },
    Vector {
        _handler: TIM1_BRK_UP_TRG_COM,
    },
    Vector { _handler: TIM1_CC },
    Vector { _reserved: 0 },
    Vector { _handler: TIM3 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: TIM14 },
    Vector { _reserved: 0 },
    Vector { _handler: TIM16 },
    Vector { _handler: TIM17 },
    Vector { _handler: I2C },
    Vector { _reserved: 0 },
    Vector { _handler: SPI },
    Vector { _reserved: 0 },
    Vector { _handler: USART1 },
    Vector { _handler: USART2 },
];
///Enumeration of all the interrupts.
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    ///0 - Window watchdog interrupt
    WWDG = 0,
    ///1 - VDDIO2 monitor interrupt (EXTI line 34
    PVM = 1,
    ///2 - RTC interrupts (EXTI lines 19)
    RTC = 2,
    ///3 - Flash global interrupt
    FLASH = 3,
    ///4 - RCC global interrupt
    RCC = 4,
    ///5 - EXTI line 0 and 1 interrupt
    EXTI0_1 = 5,
    ///6 - EXTI line 2 and 3 interrupt
    EXTI2_3 = 6,
    ///7 - EXTI line 4 and 15 interrupt
    EXTI4_15 = 7,
    ///9 - DMA1 channel 1 interrupt
    DMA1_CHANNEL1 = 9,
    ///10 - DMA1 channel 2 and 3 interrupts
    DMA1_CHANNEL2_3 = 10,
    ///11 - DMAMUX and DMA1 channel 4 and 5 interrupts
    DMAMUX_DMA1_CHANNEL4_5 = 11,
    ///12 - ADC interrupt
    ADC = 12,
    ///13 - TIM1 break, update, trigger and commutation interrupts
    TIM1_BRK_UP_TRG_COM = 13,
    ///14 - TIM1 Capture Compare interrupt
    TIM1_CC = 14,
    ///16 - TIM3 gloabal interrupt
    TIM3 = 16,
    ///19 - TIM14 gloabal interrupt
    TIM14 = 19,
    ///21 - TIM16 global interrupt
    TIM16 = 21,
    ///22 - TIM17 global interrupt
    TIM17 = 22,
    ///23 - global interrupt (combined with EXTI 23)
    I2C = 23,
    ///25 - SPI/I2S global interrupt
    SPI = 25,
    ///27 - USART1 global interrupt (combined with EXTI 25)
    USART1 = 27,
    ///28 - USART2 global interrupt (combined with EXTI 25)
    USART2 = 28,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
///Analog to Digital Converter
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#ADC)
pub type ADC = crate::Periph<adc::RegisterBlock, 0x4001_2400>;
impl core::fmt::Debug for ADC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC").finish()
    }
}
///Analog to Digital Converter
pub mod adc;
///Cyclic redundancy check calculation unit
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#CRC)
pub type CRC = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for CRC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CRC").finish()
    }
}
///Cyclic redundancy check calculation unit
pub mod crc;
///DBG register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#DBG)
pub type DBG = crate::Periph<dbg::RegisterBlock, 0x4001_5800>;
impl core::fmt::Debug for DBG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DBG").finish()
    }
}
///DBG register block
pub mod dbg;
///DMA controller
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#DMA)
pub type DMA = crate::Periph<dma::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for DMA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMA").finish()
    }
}
///DMA controller
pub mod dma;
///DMAMUX register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#DMAMUX)
pub type DMAMUX = crate::Periph<dmamux::RegisterBlock, 0x4002_0800>;
impl core::fmt::Debug for DMAMUX {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMAMUX").finish()
    }
}
///DMAMUX register block
pub mod dmamux;
///EXTI address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#EXTI)
pub type EXTI = crate::Periph<exti::RegisterBlock, 0x4002_1800>;
impl core::fmt::Debug for EXTI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EXTI").finish()
    }
}
///EXTI address block description
pub mod exti;
///FLASH register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#FLASH)
pub type FLASH = crate::Periph<flash::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for FLASH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FLASH").finish()
    }
}
///FLASH register block
pub mod flash;
///GPIOA address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#GPIOA)
pub type GPIOA = crate::Periph<gpioa::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for GPIOA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOA").finish()
    }
}
///GPIOA address block description
pub mod gpioa;
///GPIOB address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#GPIOB)
pub type GPIOB = crate::Periph<gpiob::RegisterBlock, 0x5000_0400>;
impl core::fmt::Debug for GPIOB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOB").finish()
    }
}
///GPIOB address block description
pub mod gpiob;
///GPIOC address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#GPIOC)
pub type GPIOC = crate::Periph<gpioc::RegisterBlock, 0x5000_0800>;
impl core::fmt::Debug for GPIOC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOC").finish()
    }
}
///GPIOC address block description
pub mod gpioc;
///GPIOD address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#GPIOD)
pub type GPIOD = crate::Periph<gpiod::RegisterBlock, 0x5000_0c00>;
impl core::fmt::Debug for GPIOD {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOD").finish()
    }
}
///GPIOD address block description
pub mod gpiod;
///GPIOF address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#GPIOF)
pub type GPIOF = crate::Periph<gpiof::RegisterBlock, 0x5000_1400>;
impl core::fmt::Debug for GPIOF {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOF").finish()
    }
}
///GPIOF address block description
pub mod gpiof;
///I2C register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#I2C1)
pub type I2C1 = crate::Periph<i2c1::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
///I2C register block
pub mod i2c1;
///IWDG register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#IWDG)
pub type IWDG = crate::Periph<iwdg::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for IWDG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IWDG").finish()
    }
}
///IWDG register block
pub mod iwdg;
///PWR address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#PWR)
pub type PWR = crate::Periph<pwr::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for PWR {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PWR").finish()
    }
}
///PWR address block description
pub mod pwr;
///RCC address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#RCC)
pub type RCC = crate::Periph<rcc::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for RCC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RCC").finish()
    }
}
///RCC address block description
pub mod rcc;
///RTC register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#RTC)
pub type RTC = crate::Periph<rtc::RegisterBlock, 0x4000_2800>;
impl core::fmt::Debug for RTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RTC").finish()
    }
}
///RTC register block
pub mod rtc;
///Serial peripheral interface
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#SPI1)
pub type SPI1 = crate::Periph<spi1::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for SPI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI1").finish()
    }
}
///Serial peripheral interface
pub mod spi1;
///SYSCFG register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#SYSCFG)
pub type SYSCFG = crate::Periph<syscfg::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for SYSCFG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSCFG").finish()
    }
}
///SYSCFG register block
pub mod syscfg;
///Advanced-control timer
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#TIM1)
pub type TIM1 = crate::Periph<tim1::RegisterBlock, 0x4001_2c00>;
impl core::fmt::Debug for TIM1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM1").finish()
    }
}
///Advanced-control timer
pub mod tim1;
///General-purpose timer
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#TIM3)
pub type TIM3 = crate::Periph<tim3::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for TIM3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM3").finish()
    }
}
///General-purpose timer
pub mod tim3;
///General-purpose timers
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#TIM14)
pub type TIM14 = crate::Periph<tim14::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for TIM14 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM14").finish()
    }
}
///General-purpose timers
pub mod tim14;
///General-purpose timers
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#TIM16)
pub type TIM16 = crate::Periph<tim16::RegisterBlock, 0x4001_4400>;
impl core::fmt::Debug for TIM16 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM16").finish()
    }
}
///General-purpose timers
pub mod tim16;
///General-purpose timers
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#TIM17)
pub type TIM17 = crate::Periph<tim17::RegisterBlock, 0x4001_4800>;
impl core::fmt::Debug for TIM17 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM17").finish()
    }
}
///General-purpose timers
pub mod tim17;
///USART register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#USART1)
pub type USART1 = crate::Periph<usart1::RegisterBlock, 0x4001_3800>;
impl core::fmt::Debug for USART1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART1").finish()
    }
}
///USART register block
pub mod usart1;
///USART register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#USART1)
pub type USART2 = crate::Periph<usart1::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for USART2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART2").finish()
    }
}
///USART register block
pub use self::usart1 as usart2;
///WWDG register block
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32C031.html#WWDG)
pub type WWDG = crate::Periph<wwdg::RegisterBlock, 0x4000_2c00>;
impl core::fmt::Debug for WWDG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WWDG").finish()
    }
}
///WWDG register block
pub mod wwdg;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
/// All the peripherals.
#[allow(non_snake_case)]
pub struct Peripherals {
    ///ADC
    pub ADC: ADC,
    ///CRC
    pub CRC: CRC,
    ///DBG
    pub DBG: DBG,
    ///DMA
    pub DMA: DMA,
    ///DMAMUX
    pub DMAMUX: DMAMUX,
    ///EXTI
    pub EXTI: EXTI,
    ///FLASH
    pub FLASH: FLASH,
    ///GPIOA
    pub GPIOA: GPIOA,
    ///GPIOB
    pub GPIOB: GPIOB,
    ///GPIOC
    pub GPIOC: GPIOC,
    ///GPIOD
    pub GPIOD: GPIOD,
    ///GPIOF
    pub GPIOF: GPIOF,
    ///I2C1
    pub I2C1: I2C1,
    ///IWDG
    pub IWDG: IWDG,
    ///PWR
    pub PWR: PWR,
    ///RCC
    pub RCC: RCC,
    ///RTC
    pub RTC: RTC,
    ///SPI1
    pub SPI1: SPI1,
    ///SYSCFG
    pub SYSCFG: SYSCFG,
    ///TIM1
    pub TIM1: TIM1,
    ///TIM3
    pub TIM3: TIM3,
    ///TIM14
    pub TIM14: TIM14,
    ///TIM16
    pub TIM16: TIM16,
    ///TIM17
    pub TIM17: TIM17,
    ///USART1
    pub USART1: USART1,
    ///USART2
    pub USART2: USART2,
    ///WWDG
    pub WWDG: WWDG,
}
impl Peripherals {
    /// Returns all the peripherals *once*.
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    /// Unchecked version of `Peripherals::take`.
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ADC: ADC::steal(),
            CRC: CRC::steal(),
            DBG: DBG::steal(),
            DMA: DMA::steal(),
            DMAMUX: DMAMUX::steal(),
            EXTI: EXTI::steal(),
            FLASH: FLASH::steal(),
            GPIOA: GPIOA::steal(),
            GPIOB: GPIOB::steal(),
            GPIOC: GPIOC::steal(),
            GPIOD: GPIOD::steal(),
            GPIOF: GPIOF::steal(),
            I2C1: I2C1::steal(),
            IWDG: IWDG::steal(),
            PWR: PWR::steal(),
            RCC: RCC::steal(),
            RTC: RTC::steal(),
            SPI1: SPI1::steal(),
            SYSCFG: SYSCFG::steal(),
            TIM1: TIM1::steal(),
            TIM3: TIM3::steal(),
            TIM14: TIM14::steal(),
            TIM16: TIM16::steal(),
            TIM17: TIM17::steal(),
            USART1: USART1::steal(),
            USART2: USART2::steal(),
            WWDG: WWDG::steal(),
        }
    }
}
