///Register `EXTI_RPR2` reader
pub type R = crate::R<EXTI_RPR2rs>;
///Register `EXTI_RPR2` writer
pub type W = crate::W<EXTI_RPR2rs>;
/**Rising edge event pending for configurable line 34 Each bit is set upon a rising edge event generated by hardware or by software (through the EXTI_SWIER2 register) on the line 34. Each bit is cleared by writing 1 into it.

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RPIF34 {
    ///0: No rising edge trigger request occurred
    B0x0 = 0,
    ///1: Rising edge trigger request occurred
    B0x1 = 1,
}
impl From<RPIF34> for bool {
    #[inline(always)]
    fn from(variant: RPIF34) -> Self {
        variant as u8 != 0
    }
}
///Field `RPIF34` reader - Rising edge event pending for configurable line 34 Each bit is set upon a rising edge event generated by hardware or by software (through the EXTI_SWIER2 register) on the line 34. Each bit is cleared by writing 1 into it.
pub type RPIF34_R = crate::BitReader<RPIF34>;
impl RPIF34_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> RPIF34 {
        match self.bits {
            false => RPIF34::B0x0,
            true => RPIF34::B0x1,
        }
    }
    ///No rising edge trigger request occurred
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == RPIF34::B0x0
    }
    ///Rising edge trigger request occurred
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == RPIF34::B0x1
    }
}
///Field `RPIF34` writer - Rising edge event pending for configurable line 34 Each bit is set upon a rising edge event generated by hardware or by software (through the EXTI_SWIER2 register) on the line 34. Each bit is cleared by writing 1 into it.
pub type RPIF34_W<'a, REG> = crate::BitWriter<'a, REG, RPIF34>;
impl<'a, REG> RPIF34_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///No rising edge trigger request occurred
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(RPIF34::B0x0)
    }
    ///Rising edge trigger request occurred
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(RPIF34::B0x1)
    }
}
impl R {
    ///Bit 2 - Rising edge event pending for configurable line 34 Each bit is set upon a rising edge event generated by hardware or by software (through the EXTI_SWIER2 register) on the line 34. Each bit is cleared by writing 1 into it.
    #[inline(always)]
    pub fn rpif34(&self) -> RPIF34_R {
        RPIF34_R::new(((self.bits >> 2) & 1) != 0)
    }
}
impl core::fmt::Debug for R {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EXTI_RPR2")
            .field("rpif34", &self.rpif34())
            .finish()
    }
}
impl W {
    ///Bit 2 - Rising edge event pending for configurable line 34 Each bit is set upon a rising edge event generated by hardware or by software (through the EXTI_SWIER2 register) on the line 34. Each bit is cleared by writing 1 into it.
    #[inline(always)]
    pub fn rpif34(&mut self) -> RPIF34_W<'_, EXTI_RPR2rs> {
        RPIF34_W::new(self, 2)
    }
}
/**EXTI rising edge pending register 2

You can [`read`](crate::Reg::read) this register and get [`exti_rpr2::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`exti_rpr2::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).

See register [structure](https://stm32-rs.github.io/stm32-rs/STM32C051.html#EXTI:EXTI_RPR2)*/
pub struct EXTI_RPR2rs;
impl crate::RegisterSpec for EXTI_RPR2rs {
    type Ux = u32;
}
///`read()` method returns [`exti_rpr2::R`](R) reader structure
impl crate::Readable for EXTI_RPR2rs {}
///`write(|w| ..)` method takes [`exti_rpr2::W`](W) writer structure
impl crate::Writable for EXTI_RPR2rs {
    type Safety = crate::Unsafe;
}
///`reset()` method sets EXTI_RPR2 to value 0
impl crate::Resettable for EXTI_RPR2rs {}
