/*!Peripheral access API for STM32WL33 microcontrollers (generated using svd2rust v0.37.1 (773caae 2025-10-19))

You can find an overview of the generated API [here].

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.

[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased
[repository]: https://github.com/rust-embedded/svd2rust*/
///Number available in the NVIC for configuring priority
pub const NVIC_PRIO_BITS: u8 = 4;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[cfg(feature = "rt")]
extern "C" {
    fn FLASH();
    fn RCC();
    fn PVD();
    fn I2C1();
    fn I2C2();
    fn SPI1();
    fn SPI3();
    fn USART();
    fn LPUART();
    fn TIM2();
    fn RTC();
    fn ADC();
    fn AES();
    fn GPIOA();
    fn GPIOB();
    fn DMA();
    fn LPAWUR();
    fn COMP();
    fn MR_SUBG_BUSY();
    fn MR_SUBG();
    fn TX_RX_SEQUENCE();
    fn CPU_WKUP();
    fn SUBG_WKUP();
    fn DAC();
    fn TIM16();
    fn LCD();
    fn LCSC();
    fn LC_ACTIVITY();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 30] = [
    Vector { _handler: FLASH },
    Vector { _handler: RCC },
    Vector { _handler: PVD },
    Vector { _handler: I2C1 },
    Vector { _handler: I2C2 },
    Vector { _handler: SPI1 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI3 },
    Vector { _handler: USART },
    Vector { _handler: LPUART },
    Vector { _handler: TIM2 },
    Vector { _handler: RTC },
    Vector { _handler: ADC },
    Vector { _handler: AES },
    Vector { _reserved: 0 },
    Vector { _handler: GPIOA },
    Vector { _handler: GPIOB },
    Vector { _handler: DMA },
    Vector { _handler: LPAWUR },
    Vector { _handler: COMP },
    Vector {
        _handler: MR_SUBG_BUSY,
    },
    Vector { _handler: MR_SUBG },
    Vector {
        _handler: TX_RX_SEQUENCE,
    },
    Vector { _handler: CPU_WKUP },
    Vector {
        _handler: SUBG_WKUP,
    },
    Vector { _handler: DAC },
    Vector { _handler: TIM16 },
    Vector { _handler: LCD },
    Vector { _handler: LCSC },
    Vector {
        _handler: LC_ACTIVITY,
    },
];
///Enumeration of all the interrupts.
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    ///0 - Non-volatile memory (flash) controller
    FLASH = 0,
    ///1 - Reset and Clock Controller
    RCC = 1,
    ///2 - PVD / BORH
    PVD = 2,
    ///3 - I2C1 interrupt
    I2C1 = 3,
    ///4 - I2C2 interrupt
    I2C2 = 4,
    ///5 - SPI1 interrupt
    SPI1 = 5,
    ///7 - SPI3 interrupt
    SPI3 = 7,
    ///8 - USART interrupt
    USART = 8,
    ///9 - LPUART interrupt
    LPUART = 9,
    ///10 - TIM2 interrupt
    TIM2 = 10,
    ///11 - RTC interrupt
    RTC = 11,
    ///12 - ADC interrupt
    ADC = 12,
    ///13 - AES interrupt
    AES = 13,
    ///15 - GPIOA interrupt
    GPIOA = 15,
    ///16 - GPIOB interrupt
    GPIOB = 16,
    ///17 - DMA interrupt
    DMA = 17,
    ///18 - LPAWUR interrupt
    LPAWUR = 18,
    ///19 - Comp interrupt through SYSCFG
    COMP = 19,
    ///20 - MR_SUBG Busy interrupt
    MR_SUBG_BUSY = 20,
    ///21 - MR_SUBG interrupt
    MR_SUBG = 21,
    ///22 - MR_SUBG TX/RX Sequence interrupt
    TX_RX_SEQUENCE = 22,
    ///23 - CPU Wakeup interrupt
    CPU_WKUP = 23,
    ///24 - SUBG Wakeup interrupt
    SUBG_WKUP = 24,
    ///25 - DAC interrupt
    DAC = 25,
    ///26 - TIM16 interrupt
    TIM16 = 26,
    ///27 - LCD interrupt
    LCD = 27,
    ///28 - LCSC interrupt
    LCSC = 28,
    ///29 - LCSC LC_ACTIVITY interrupt
    LC_ACTIVITY = 29,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
///ADC address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#ADC)
pub type ADC = crate::Periph<adc::RegisterBlock, 0x4100_6000>;
impl core::fmt::Debug for ADC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC").finish()
    }
}
///ADC address block description
pub mod adc;
///AES
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#AES)
pub type AES = crate::Periph<aes::RegisterBlock, 0x4890_0000>;
impl core::fmt::Debug for AES {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AES").finish()
    }
}
///AES
pub mod aes;
///CRC
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#CRC)
pub type CRC = crate::Periph<crc::RegisterBlock, 0x4820_0000>;
impl core::fmt::Debug for CRC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CRC").finish()
    }
}
///CRC
pub mod crc;
///COMP address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#COMP)
pub type COMP = crate::Periph<comp::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for COMP {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("COMP").finish()
    }
}
///COMP address block description
pub mod comp;
///DAC address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#DAC)
pub type DAC = crate::Periph<dac::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for DAC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DAC").finish()
    }
}
///DAC address block description
pub mod dac;
///DBGMCU
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#DBGMCU)
pub type DBGMCU = crate::Periph<dbgmcu::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for DBGMCU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DBGMCU").finish()
    }
}
///DBGMCU
pub mod dbgmcu;
///DMAMUX address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#DMAMUX)
pub type DMAMUX = crate::Periph<dmamux::RegisterBlock, 0x4880_0000>;
impl core::fmt::Debug for DMAMUX {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMAMUX").finish()
    }
}
///DMAMUX address block description
pub mod dmamux;
///DMA address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#DMA)
pub type DMA = crate::Periph<dma::RegisterBlock, 0x4870_0000>;
impl core::fmt::Debug for DMA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMA").finish()
    }
}
///DMA address block description
pub mod dma;
///DYNAMIC_REG
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#DYNAMIC_REG)
pub type DYNAMIC_REG = crate::Periph<dynamic_reg::RegisterBlock, 0x4900_0500>;
impl core::fmt::Debug for DYNAMIC_REG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DYNAMIC_REG").finish()
    }
}
///DYNAMIC_REG
pub mod dynamic_reg;
///4kb addressable space
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#FLASH_CTRL)
pub type FLASH_CTRL = crate::Periph<flash_ctrl::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for FLASH_CTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FLASH_CTRL").finish()
    }
}
///4kb addressable space
pub mod flash_ctrl;
///GPIOA
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#GPIOA)
pub type GPIOA = crate::Periph<gpioa::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for GPIOA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOA").finish()
    }
}
///GPIOA
pub mod gpioa;
///GPIOB
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#GPIOB)
pub type GPIOB = crate::Periph<gpiob::RegisterBlock, 0x4810_0000>;
impl core::fmt::Debug for GPIOB {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPIOB").finish()
    }
}
///GPIOB
pub mod gpiob;
///I2C1
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#I2C1)
pub type I2C1 = crate::Periph<i2c1::RegisterBlock, 0x4100_0000>;
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
///I2C1
pub mod i2c1;
///I2C2
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#I2C2)
pub type I2C2 = crate::Periph<i2c2::RegisterBlock, 0x4100_1000>;
impl core::fmt::Debug for I2C2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C2").finish()
    }
}
///I2C2
pub mod i2c2;
///IWDG
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#IWDG)
pub type IWDG = crate::Periph<iwdg::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for IWDG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IWDG").finish()
    }
}
///IWDG
pub mod iwdg;
///LCD
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#LCD)
pub type LCD = crate::Periph<lcd::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for LCD {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LCD").finish()
    }
}
///LCD
pub mod lcd;
///LPUART
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#LPUART)
pub type LPUART = crate::Periph<lpuart::RegisterBlock, 0x4100_5000>;
impl core::fmt::Debug for LPUART {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LPUART").finish()
    }
}
///LPUART
pub mod lpuart;
///LCSC
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#LCSC)
pub type LCSC = crate::Periph<lcsc::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for LCSC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LCSC").finish()
    }
}
///LCSC
pub mod lcsc;
///LPAWUR
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#LPAWUR)
pub type LPAWUR = crate::Periph<lpawur::RegisterBlock, 0x4900_1000>;
impl core::fmt::Debug for LPAWUR {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LPAWUR").finish()
    }
}
///LPAWUR
pub mod lpawur;
///MISC
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#MISC)
pub type MISC = crate::Periph<misc::RegisterBlock, 0x4900_0700>;
impl core::fmt::Debug for MISC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MISC").finish()
    }
}
///MISC
pub mod misc;
///MR_SUBG
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#MR_SUBG)
pub type MR_SUBG = crate::Periph<mr_subg::RegisterBlock, 0x4900_0000>;
impl core::fmt::Debug for MR_SUBG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MR_SUBG").finish()
    }
}
///MR_SUBG
pub mod mr_subg;
///PWRC
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#PWRC)
pub type PWRC = crate::Periph<pwrc::RegisterBlock, 0x4850_0000>;
impl core::fmt::Debug for PWRC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PWRC").finish()
    }
}
///PWRC
pub mod pwrc;
///RCC
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#RCC)
pub type RCC = crate::Periph<rcc::RegisterBlock, 0x4840_0000>;
impl core::fmt::Debug for RCC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RCC").finish()
    }
}
///RCC
pub mod rcc;
///RETAINED
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#RETAINED)
pub type RETAINED = crate::Periph<retained::RegisterBlock, 0x4900_0780>;
impl core::fmt::Debug for RETAINED {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RETAINED").finish()
    }
}
///RETAINED
pub mod retained;
///RNG
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#RNG)
pub type RNG = crate::Periph<rng::RegisterBlock, 0x4860_0000>;
impl core::fmt::Debug for RNG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RNG").finish()
    }
}
///RNG
pub mod rng;
///RTC
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#RTC)
pub type RTC = crate::Periph<rtc::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for RTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RTC").finish()
    }
}
///RTC
pub mod rtc;
///SPI
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#SPI)
pub type SPI = crate::Periph<spi::RegisterBlock, 0x4100_2000>;
impl core::fmt::Debug for SPI {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI").finish()
    }
}
///SPI
pub mod spi;
///SPI3
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#SPI3)
pub type SPI3 = crate::Periph<spi3::RegisterBlock, 0x4100_7000>;
impl core::fmt::Debug for SPI3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI3").finish()
    }
}
///SPI3
pub mod spi3;
///SYSTEM_CTRL
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#SYSTEM_CTRL)
pub type SYSTEM_CTRL = crate::Periph<system_ctrl::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for SYSTEM_CTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSTEM_CTRL").finish()
    }
}
///SYSTEM_CTRL
pub mod system_ctrl;
///SWITCHABLE
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#SWITCHABLE)
pub type SWITCHABLE = crate::Periph<switchable::RegisterBlock, 0x4900_1040>;
impl core::fmt::Debug for SWITCHABLE {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SWITCHABLE").finish()
    }
}
///SWITCHABLE
pub mod switchable;
///STATUS
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#STATUS)
pub type STATUS = crate::Periph<status::RegisterBlock, 0x4900_0600>;
impl core::fmt::Debug for STATUS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("STATUS").finish()
    }
}
///STATUS
pub mod status;
///STATIC
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#STATIC)
pub type STATIC = crate::Periph<static_::RegisterBlock, 0x4900_0400>;
impl core::fmt::Debug for STATIC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("STATIC").finish()
    }
}
///STATIC
pub mod static_;
///TIM16 address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#TIM16)
pub type TIM16 = crate::Periph<tim16::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for TIM16 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM16").finish()
    }
}
///TIM16 address block description
pub mod tim16;
///TIM2 address block description
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#TIM2)
pub type TIM2 = crate::Periph<tim2::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for TIM2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM2").finish()
    }
}
///TIM2 address block description
pub mod tim2;
///USART
///
///See peripheral [structure](https://stm32-rs.github.io/stm32-rs/STM32WL33.html#USART)
pub type USART = crate::Periph<usart::RegisterBlock, 0x4100_4000>;
impl core::fmt::Debug for USART {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USART").finish()
    }
}
///USART
pub mod usart;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
/// All the peripherals.
#[allow(non_snake_case)]
pub struct Peripherals {
    ///ADC
    pub ADC: ADC,
    ///AES
    pub AES: AES,
    ///CRC
    pub CRC: CRC,
    ///COMP
    pub COMP: COMP,
    ///DAC
    pub DAC: DAC,
    ///DBGMCU
    pub DBGMCU: DBGMCU,
    ///DMAMUX
    pub DMAMUX: DMAMUX,
    ///DMA
    pub DMA: DMA,
    ///DYNAMIC_REG
    pub DYNAMIC_REG: DYNAMIC_REG,
    ///FLASH_CTRL
    pub FLASH_CTRL: FLASH_CTRL,
    ///GPIOA
    pub GPIOA: GPIOA,
    ///GPIOB
    pub GPIOB: GPIOB,
    ///I2C1
    pub I2C1: I2C1,
    ///I2C2
    pub I2C2: I2C2,
    ///IWDG
    pub IWDG: IWDG,
    ///LCD
    pub LCD: LCD,
    ///LPUART
    pub LPUART: LPUART,
    ///LCSC
    pub LCSC: LCSC,
    ///LPAWUR
    pub LPAWUR: LPAWUR,
    ///MISC
    pub MISC: MISC,
    ///MR_SUBG
    pub MR_SUBG: MR_SUBG,
    ///PWRC
    pub PWRC: PWRC,
    ///RCC
    pub RCC: RCC,
    ///RETAINED
    pub RETAINED: RETAINED,
    ///RNG
    pub RNG: RNG,
    ///RTC
    pub RTC: RTC,
    ///SPI
    pub SPI: SPI,
    ///SPI3
    pub SPI3: SPI3,
    ///SYSTEM_CTRL
    pub SYSTEM_CTRL: SYSTEM_CTRL,
    ///SWITCHABLE
    pub SWITCHABLE: SWITCHABLE,
    ///STATUS
    pub STATUS: STATUS,
    ///STATIC
    pub STATIC: STATIC,
    ///TIM16
    pub TIM16: TIM16,
    ///TIM2
    pub TIM2: TIM2,
    ///USART
    pub USART: USART,
}
impl Peripherals {
    /// Returns all the peripherals *once*.
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    /// Unchecked version of `Peripherals::take`.
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ADC: ADC::steal(),
            AES: AES::steal(),
            CRC: CRC::steal(),
            COMP: COMP::steal(),
            DAC: DAC::steal(),
            DBGMCU: DBGMCU::steal(),
            DMAMUX: DMAMUX::steal(),
            DMA: DMA::steal(),
            DYNAMIC_REG: DYNAMIC_REG::steal(),
            FLASH_CTRL: FLASH_CTRL::steal(),
            GPIOA: GPIOA::steal(),
            GPIOB: GPIOB::steal(),
            I2C1: I2C1::steal(),
            I2C2: I2C2::steal(),
            IWDG: IWDG::steal(),
            LCD: LCD::steal(),
            LPUART: LPUART::steal(),
            LCSC: LCSC::steal(),
            LPAWUR: LPAWUR::steal(),
            MISC: MISC::steal(),
            MR_SUBG: MR_SUBG::steal(),
            PWRC: PWRC::steal(),
            RCC: RCC::steal(),
            RETAINED: RETAINED::steal(),
            RNG: RNG::steal(),
            RTC: RTC::steal(),
            SPI: SPI::steal(),
            SPI3: SPI3::steal(),
            SYSTEM_CTRL: SYSTEM_CTRL::steal(),
            SWITCHABLE: SWITCHABLE::steal(),
            STATUS: STATUS::steal(),
            STATIC: STATIC::steal(),
            TIM16: TIM16::steal(),
            TIM2: TIM2::steal(),
            USART: USART::steal(),
        }
    }
}
