#[doc = "Register `ILS` reader"]
pub type R = crate::R<ILSrs>;
#[doc = "Register `ILS` writer"]
pub type W = crate::W<ILSrs>;
#[doc = "Field `RXFIFO0` reader - RX FIFO bit grouping the following interruption"]
pub type RXFIFO0_R = crate::BitReader;
#[doc = "Field `RXFIFO0` writer - RX FIFO bit grouping the following interruption"]
pub type RXFIFO0_W<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `RXFIFO1` reader - RX FIFO bit grouping the following interruption"]
pub type RXFIFO1_R = crate::BitReader;
#[doc = "Field `RXFIFO1` writer - RX FIFO bit grouping the following interruption"]
pub type RXFIFO1_W<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `SMSG` reader - Status message bit grouping the following interruption"]
pub type SMSG_R = crate::BitReader;
#[doc = "Field `SMSG` writer - Status message bit grouping the following interruption"]
pub type SMSG_W<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `TFERR` reader - TX FIFO error grouping the following interruption"]
pub type TFERR_R = crate::BitReader;
#[doc = "Field `TFERR` writer - TX FIFO error grouping the following interruption"]
pub type TFERR_W<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `MISC` reader - Interrupt regrouping the following interruption"]
pub type MISC_R = crate::BitReader;
#[doc = "Field `MISC` writer - Interrupt regrouping the following interruption"]
pub type MISC_W<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `BERR` reader - Bit and line error grouping the following interruption"]
pub type BERR_R = crate::BitReader;
#[doc = "Field `BERR` writer - Bit and line error grouping the following interruption"]
pub type BERR_W<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `PERR` reader - Protocol error grouping the following interruption"]
pub type PERR_R = crate::BitReader;
#[doc = "Field `PERR` writer - Protocol error grouping the following interruption"]
pub type PERR_W<'a, REG> = crate::BitWriter<'a, REG>;
impl R {
    #[doc = "Bit 0 - RX FIFO bit grouping the following interruption"]
    #[inline(always)]
    pub fn rxfifo0(&self) -> RXFIFO0_R {
        RXFIFO0_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - RX FIFO bit grouping the following interruption"]
    #[inline(always)]
    pub fn rxfifo1(&self) -> RXFIFO1_R {
        RXFIFO1_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Status message bit grouping the following interruption"]
    #[inline(always)]
    pub fn smsg(&self) -> SMSG_R {
        SMSG_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - TX FIFO error grouping the following interruption"]
    #[inline(always)]
    pub fn tferr(&self) -> TFERR_R {
        TFERR_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Interrupt regrouping the following interruption"]
    #[inline(always)]
    pub fn misc(&self) -> MISC_R {
        MISC_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Bit and line error grouping the following interruption"]
    #[inline(always)]
    pub fn berr(&self) -> BERR_R {
        BERR_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - Protocol error grouping the following interruption"]
    #[inline(always)]
    pub fn perr(&self) -> PERR_R {
        PERR_R::new(((self.bits >> 6) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - RX FIFO bit grouping the following interruption"]
    #[inline(always)]
    #[must_use]
    pub fn rxfifo0(&mut self) -> RXFIFO0_W<ILSrs> {
        RXFIFO0_W::new(self, 0)
    }
    #[doc = "Bit 1 - RX FIFO bit grouping the following interruption"]
    #[inline(always)]
    #[must_use]
    pub fn rxfifo1(&mut self) -> RXFIFO1_W<ILSrs> {
        RXFIFO1_W::new(self, 1)
    }
    #[doc = "Bit 2 - Status message bit grouping the following interruption"]
    #[inline(always)]
    #[must_use]
    pub fn smsg(&mut self) -> SMSG_W<ILSrs> {
        SMSG_W::new(self, 2)
    }
    #[doc = "Bit 3 - TX FIFO error grouping the following interruption"]
    #[inline(always)]
    #[must_use]
    pub fn tferr(&mut self) -> TFERR_W<ILSrs> {
        TFERR_W::new(self, 3)
    }
    #[doc = "Bit 4 - Interrupt regrouping the following interruption"]
    #[inline(always)]
    #[must_use]
    pub fn misc(&mut self) -> MISC_W<ILSrs> {
        MISC_W::new(self, 4)
    }
    #[doc = "Bit 5 - Bit and line error grouping the following interruption"]
    #[inline(always)]
    #[must_use]
    pub fn berr(&mut self) -> BERR_W<ILSrs> {
        BERR_W::new(self, 5)
    }
    #[doc = "Bit 6 - Protocol error grouping the following interruption"]
    #[inline(always)]
    #[must_use]
    pub fn perr(&mut self) -> PERR_W<ILSrs> {
        PERR_W::new(self, 6)
    }
}
#[doc = "The Interrupt Line Select register assigns an interrupt generated by a specific interrupt flag from the Interrupt Register to one of the two module interrupt lines. For interrupt generation the respective interrupt line has to be enabled via ILE\\[EINT0\\]
and ILE\\[EINT1\\].\n\nYou can [`read`](crate::generic::Reg::read) this register and get [`ils::R`](R).  You can [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`write_with_zero`](crate::generic::Reg::write_with_zero) this register using [`ils::W`](W). You can also [`modify`](crate::generic::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct ILSrs;
impl crate::RegisterSpec for ILSrs {
    type Ux = u32;
}
#[doc = "`read()` method returns [`ils::R`](R) reader structure"]
impl crate::Readable for ILSrs {}
#[doc = "`write(|w| ..)` method takes [`ils::W`](W) writer structure"]
impl crate::Writable for ILSrs {
    type Safety = crate::Unsafe;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
}
#[doc = "`reset()` method sets ILS to value 0"]
impl crate::Resettable for ILSrs {
    const RESET_VALUE: u32 = 0;
}
