///Register `TIM1_CR1` reader
pub type R = crate::R<TIM1_CR1rs>;
///Register `TIM1_CR1` writer
pub type W = crate::W<TIM1_CR1rs>;
/**Counter enable Note: External clock, gated mode and encoder mode can work only if the CEN bit has been previously set by software. However trigger mode can set the CEN bit automatically by hardware.

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CEN {
    ///0: Counter disabled
    B0x0 = 0,
    ///1: Counter enabled
    B0x1 = 1,
}
impl From<CEN> for bool {
    #[inline(always)]
    fn from(variant: CEN) -> Self {
        variant as u8 != 0
    }
}
///Field `CEN` reader - Counter enable Note: External clock, gated mode and encoder mode can work only if the CEN bit has been previously set by software. However trigger mode can set the CEN bit automatically by hardware.
pub type CEN_R = crate::BitReader<CEN>;
impl CEN_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> CEN {
        match self.bits {
            false => CEN::B0x0,
            true => CEN::B0x1,
        }
    }
    ///Counter disabled
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == CEN::B0x0
    }
    ///Counter enabled
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == CEN::B0x1
    }
}
///Field `CEN` writer - Counter enable Note: External clock, gated mode and encoder mode can work only if the CEN bit has been previously set by software. However trigger mode can set the CEN bit automatically by hardware.
pub type CEN_W<'a, REG> = crate::BitWriter<'a, REG, CEN>;
impl<'a, REG> CEN_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///Counter disabled
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(CEN::B0x0)
    }
    ///Counter enabled
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(CEN::B0x1)
    }
}
/**Update disable This bit is set and cleared by software to enable/disable UEV event generation. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller Buffered registers are then loaded with their preload values.

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UDIS {
    ///0: UEV enabled. The Update (UEV) event is generated by one of the following events:
    B0x0 = 0,
    ///1: UEV disabled. The Update event is not generated, shadow registers keep their value (ARR, PSC, CCRx). However the counter and the prescaler are reinitialized if the UG bit is set or if a hardware reset is received from the slave mode controller.
    B0x1 = 1,
}
impl From<UDIS> for bool {
    #[inline(always)]
    fn from(variant: UDIS) -> Self {
        variant as u8 != 0
    }
}
///Field `UDIS` reader - Update disable This bit is set and cleared by software to enable/disable UEV event generation. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller Buffered registers are then loaded with their preload values.
pub type UDIS_R = crate::BitReader<UDIS>;
impl UDIS_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> UDIS {
        match self.bits {
            false => UDIS::B0x0,
            true => UDIS::B0x1,
        }
    }
    ///UEV enabled. The Update (UEV) event is generated by one of the following events:
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == UDIS::B0x0
    }
    ///UEV disabled. The Update event is not generated, shadow registers keep their value (ARR, PSC, CCRx). However the counter and the prescaler are reinitialized if the UG bit is set or if a hardware reset is received from the slave mode controller.
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == UDIS::B0x1
    }
}
///Field `UDIS` writer - Update disable This bit is set and cleared by software to enable/disable UEV event generation. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller Buffered registers are then loaded with their preload values.
pub type UDIS_W<'a, REG> = crate::BitWriter<'a, REG, UDIS>;
impl<'a, REG> UDIS_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///UEV enabled. The Update (UEV) event is generated by one of the following events:
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(UDIS::B0x0)
    }
    ///UEV disabled. The Update event is not generated, shadow registers keep their value (ARR, PSC, CCRx). However the counter and the prescaler are reinitialized if the UG bit is set or if a hardware reset is received from the slave mode controller.
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(UDIS::B0x1)
    }
}
/**Update request source This bit is set and cleared by software to select the UEV event sources. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum URS {
    ///0: Any of the following events generate an update interrupt or DMA request if enabled. These events can be:
    B0x0 = 0,
    ///1: Only counter overflow/underflow generates an update interrupt or DMA request if enabled.
    B0x1 = 1,
}
impl From<URS> for bool {
    #[inline(always)]
    fn from(variant: URS) -> Self {
        variant as u8 != 0
    }
}
///Field `URS` reader - Update request source This bit is set and cleared by software to select the UEV event sources. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller
pub type URS_R = crate::BitReader<URS>;
impl URS_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> URS {
        match self.bits {
            false => URS::B0x0,
            true => URS::B0x1,
        }
    }
    ///Any of the following events generate an update interrupt or DMA request if enabled. These events can be:
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == URS::B0x0
    }
    ///Only counter overflow/underflow generates an update interrupt or DMA request if enabled.
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == URS::B0x1
    }
}
///Field `URS` writer - Update request source This bit is set and cleared by software to select the UEV event sources. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller
pub type URS_W<'a, REG> = crate::BitWriter<'a, REG, URS>;
impl<'a, REG> URS_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///Any of the following events generate an update interrupt or DMA request if enabled. These events can be:
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(URS::B0x0)
    }
    ///Only counter overflow/underflow generates an update interrupt or DMA request if enabled.
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(URS::B0x1)
    }
}
/**One pulse mode

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OPM {
    ///0: Counter is not stopped at update event
    B0x0 = 0,
    ///1: Counter stops counting at the next update event (clearing the bit CEN)
    B0x1 = 1,
}
impl From<OPM> for bool {
    #[inline(always)]
    fn from(variant: OPM) -> Self {
        variant as u8 != 0
    }
}
///Field `OPM` reader - One pulse mode
pub type OPM_R = crate::BitReader<OPM>;
impl OPM_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> OPM {
        match self.bits {
            false => OPM::B0x0,
            true => OPM::B0x1,
        }
    }
    ///Counter is not stopped at update event
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == OPM::B0x0
    }
    ///Counter stops counting at the next update event (clearing the bit CEN)
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == OPM::B0x1
    }
}
///Field `OPM` writer - One pulse mode
pub type OPM_W<'a, REG> = crate::BitWriter<'a, REG, OPM>;
impl<'a, REG> OPM_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///Counter is not stopped at update event
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(OPM::B0x0)
    }
    ///Counter stops counting at the next update event (clearing the bit CEN)
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(OPM::B0x1)
    }
}
/**Direction Note: This bit is read only when the timer is configured in Center-aligned mode or Encoder mode.

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DIR {
    ///0: Counter used as upcounter
    B0x0 = 0,
    ///1: Counter used as downcounter
    B0x1 = 1,
}
impl From<DIR> for bool {
    #[inline(always)]
    fn from(variant: DIR) -> Self {
        variant as u8 != 0
    }
}
///Field `DIR` reader - Direction Note: This bit is read only when the timer is configured in Center-aligned mode or Encoder mode.
pub type DIR_R = crate::BitReader<DIR>;
impl DIR_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> DIR {
        match self.bits {
            false => DIR::B0x0,
            true => DIR::B0x1,
        }
    }
    ///Counter used as upcounter
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == DIR::B0x0
    }
    ///Counter used as downcounter
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == DIR::B0x1
    }
}
///Field `DIR` writer - Direction Note: This bit is read only when the timer is configured in Center-aligned mode or Encoder mode.
pub type DIR_W<'a, REG> = crate::BitWriter<'a, REG, DIR>;
impl<'a, REG> DIR_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///Counter used as upcounter
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(DIR::B0x0)
    }
    ///Counter used as downcounter
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(DIR::B0x1)
    }
}
/**Center-aligned mode selection Note: Switch from edge-aligned mode to center-aligned mode as long as the counter is enabled (CEN=1) is not allowed

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum CMS {
    ///0: Edge-aligned mode. The counter counts up or down depending on the direction bit (DIR).
    B0x0 = 0,
    ///1: Center-aligned mode 1. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set only when the counter is counting down.
    B0x1 = 1,
    ///2: Center-aligned mode 2. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set only when the counter is counting up.
    B0x2 = 2,
    ///3: Center-aligned mode 3. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set both when the counter is counting up or down.
    B0x3 = 3,
}
impl From<CMS> for u8 {
    #[inline(always)]
    fn from(variant: CMS) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for CMS {
    type Ux = u8;
}
impl crate::IsEnum for CMS {}
///Field `CMS` reader - Center-aligned mode selection Note: Switch from edge-aligned mode to center-aligned mode as long as the counter is enabled (CEN=1) is not allowed
pub type CMS_R = crate::FieldReader<CMS>;
impl CMS_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> CMS {
        match self.bits {
            0 => CMS::B0x0,
            1 => CMS::B0x1,
            2 => CMS::B0x2,
            3 => CMS::B0x3,
            _ => unreachable!(),
        }
    }
    ///Edge-aligned mode. The counter counts up or down depending on the direction bit (DIR).
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == CMS::B0x0
    }
    ///Center-aligned mode 1. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set only when the counter is counting down.
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == CMS::B0x1
    }
    ///Center-aligned mode 2. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set only when the counter is counting up.
    #[inline(always)]
    pub fn is_b_0x2(&self) -> bool {
        *self == CMS::B0x2
    }
    ///Center-aligned mode 3. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set both when the counter is counting up or down.
    #[inline(always)]
    pub fn is_b_0x3(&self) -> bool {
        *self == CMS::B0x3
    }
}
///Field `CMS` writer - Center-aligned mode selection Note: Switch from edge-aligned mode to center-aligned mode as long as the counter is enabled (CEN=1) is not allowed
pub type CMS_W<'a, REG> = crate::FieldWriter<'a, REG, 2, CMS, crate::Safe>;
impl<'a, REG> CMS_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    ///Edge-aligned mode. The counter counts up or down depending on the direction bit (DIR).
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(CMS::B0x0)
    }
    ///Center-aligned mode 1. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set only when the counter is counting down.
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(CMS::B0x1)
    }
    ///Center-aligned mode 2. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set only when the counter is counting up.
    #[inline(always)]
    pub fn b_0x2(self) -> &'a mut crate::W<REG> {
        self.variant(CMS::B0x2)
    }
    ///Center-aligned mode 3. The counter counts up and down alternatively. Output compare interrupt flags of channels configured in output (CCxS=00 in TIMx_CCMRx register) are set both when the counter is counting up or down.
    #[inline(always)]
    pub fn b_0x3(self) -> &'a mut crate::W<REG> {
        self.variant(CMS::B0x3)
    }
}
/**Auto-reload preload enable

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ARPE {
    ///0: TIMx_ARR register is not buffered
    B0x0 = 0,
    ///1: TIMx_ARR register is buffered
    B0x1 = 1,
}
impl From<ARPE> for bool {
    #[inline(always)]
    fn from(variant: ARPE) -> Self {
        variant as u8 != 0
    }
}
///Field `ARPE` reader - Auto-reload preload enable
pub type ARPE_R = crate::BitReader<ARPE>;
impl ARPE_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> ARPE {
        match self.bits {
            false => ARPE::B0x0,
            true => ARPE::B0x1,
        }
    }
    ///TIMx_ARR register is not buffered
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == ARPE::B0x0
    }
    ///TIMx_ARR register is buffered
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == ARPE::B0x1
    }
}
///Field `ARPE` writer - Auto-reload preload enable
pub type ARPE_W<'a, REG> = crate::BitWriter<'a, REG, ARPE>;
impl<'a, REG> ARPE_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///TIMx_ARR register is not buffered
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(ARPE::B0x0)
    }
    ///TIMx_ARR register is buffered
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(ARPE::B0x1)
    }
}
/**Clock division This bit-field indicates the division ratio between the timer clock (CK_INT) frequency and the dead-time and sampling clock (t<sub>DTS</sub>)used by the dead-time generators and the digital filters (ETR, TIx): Note: t<sub>DTS</sub> = 1/f<sub>DTS</sub>, t<sub>CK_INT</sub> = 1/f<sub>CK_INT</sub>.

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum CKD {
    ///0: t<sub>DTS</sub>=t<sub>CK_INT</sub>
    B0x0 = 0,
    ///1: t<sub>DTS</sub>=2*t<sub>CK_INT</sub>
    B0x1 = 1,
    ///2: t<sub>DTS</sub>=4*t<sub>CK_INT</sub>
    B0x2 = 2,
    ///3: Reserved, do not program this value
    B0x3 = 3,
}
impl From<CKD> for u8 {
    #[inline(always)]
    fn from(variant: CKD) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for CKD {
    type Ux = u8;
}
impl crate::IsEnum for CKD {}
///Field `CKD` reader - Clock division This bit-field indicates the division ratio between the timer clock (CK_INT) frequency and the dead-time and sampling clock (t<sub>DTS</sub>)used by the dead-time generators and the digital filters (ETR, TIx): Note: t<sub>DTS</sub> = 1/f<sub>DTS</sub>, t<sub>CK_INT</sub> = 1/f<sub>CK_INT</sub>.
pub type CKD_R = crate::FieldReader<CKD>;
impl CKD_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> CKD {
        match self.bits {
            0 => CKD::B0x0,
            1 => CKD::B0x1,
            2 => CKD::B0x2,
            3 => CKD::B0x3,
            _ => unreachable!(),
        }
    }
    ///t<sub>DTS</sub>=t<sub>CK_INT</sub>
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == CKD::B0x0
    }
    ///t<sub>DTS</sub>=2*t<sub>CK_INT</sub>
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == CKD::B0x1
    }
    ///t<sub>DTS</sub>=4*t<sub>CK_INT</sub>
    #[inline(always)]
    pub fn is_b_0x2(&self) -> bool {
        *self == CKD::B0x2
    }
    ///Reserved, do not program this value
    #[inline(always)]
    pub fn is_b_0x3(&self) -> bool {
        *self == CKD::B0x3
    }
}
///Field `CKD` writer - Clock division This bit-field indicates the division ratio between the timer clock (CK_INT) frequency and the dead-time and sampling clock (t<sub>DTS</sub>)used by the dead-time generators and the digital filters (ETR, TIx): Note: t<sub>DTS</sub> = 1/f<sub>DTS</sub>, t<sub>CK_INT</sub> = 1/f<sub>CK_INT</sub>.
pub type CKD_W<'a, REG> = crate::FieldWriter<'a, REG, 2, CKD, crate::Safe>;
impl<'a, REG> CKD_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    ///t<sub>DTS</sub>=t<sub>CK_INT</sub>
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(CKD::B0x0)
    }
    ///t<sub>DTS</sub>=2*t<sub>CK_INT</sub>
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(CKD::B0x1)
    }
    ///t<sub>DTS</sub>=4*t<sub>CK_INT</sub>
    #[inline(always)]
    pub fn b_0x2(self) -> &'a mut crate::W<REG> {
        self.variant(CKD::B0x2)
    }
    ///Reserved, do not program this value
    #[inline(always)]
    pub fn b_0x3(self) -> &'a mut crate::W<REG> {
        self.variant(CKD::B0x3)
    }
}
/**UIF status bit remapping

Value on reset: 0*/
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UIFREMAP {
    ///0: No remapping. UIF status bit is not copied to TIMx_CNT register bit 31.
    B0x0 = 0,
    ///1: Remapping enabled. UIF status bit is copied to TIMx_CNT register bit 31.
    B0x1 = 1,
}
impl From<UIFREMAP> for bool {
    #[inline(always)]
    fn from(variant: UIFREMAP) -> Self {
        variant as u8 != 0
    }
}
///Field `UIFREMAP` reader - UIF status bit remapping
pub type UIFREMAP_R = crate::BitReader<UIFREMAP>;
impl UIFREMAP_R {
    ///Get enumerated values variant
    #[inline(always)]
    pub const fn variant(&self) -> UIFREMAP {
        match self.bits {
            false => UIFREMAP::B0x0,
            true => UIFREMAP::B0x1,
        }
    }
    ///No remapping. UIF status bit is not copied to TIMx_CNT register bit 31.
    #[inline(always)]
    pub fn is_b_0x0(&self) -> bool {
        *self == UIFREMAP::B0x0
    }
    ///Remapping enabled. UIF status bit is copied to TIMx_CNT register bit 31.
    #[inline(always)]
    pub fn is_b_0x1(&self) -> bool {
        *self == UIFREMAP::B0x1
    }
}
///Field `UIFREMAP` writer - UIF status bit remapping
pub type UIFREMAP_W<'a, REG> = crate::BitWriter<'a, REG, UIFREMAP>;
impl<'a, REG> UIFREMAP_W<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    ///No remapping. UIF status bit is not copied to TIMx_CNT register bit 31.
    #[inline(always)]
    pub fn b_0x0(self) -> &'a mut crate::W<REG> {
        self.variant(UIFREMAP::B0x0)
    }
    ///Remapping enabled. UIF status bit is copied to TIMx_CNT register bit 31.
    #[inline(always)]
    pub fn b_0x1(self) -> &'a mut crate::W<REG> {
        self.variant(UIFREMAP::B0x1)
    }
}
impl R {
    ///Bit 0 - Counter enable Note: External clock, gated mode and encoder mode can work only if the CEN bit has been previously set by software. However trigger mode can set the CEN bit automatically by hardware.
    #[inline(always)]
    pub fn cen(&self) -> CEN_R {
        CEN_R::new((self.bits & 1) != 0)
    }
    ///Bit 1 - Update disable This bit is set and cleared by software to enable/disable UEV event generation. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller Buffered registers are then loaded with their preload values.
    #[inline(always)]
    pub fn udis(&self) -> UDIS_R {
        UDIS_R::new(((self.bits >> 1) & 1) != 0)
    }
    ///Bit 2 - Update request source This bit is set and cleared by software to select the UEV event sources. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller
    #[inline(always)]
    pub fn urs(&self) -> URS_R {
        URS_R::new(((self.bits >> 2) & 1) != 0)
    }
    ///Bit 3 - One pulse mode
    #[inline(always)]
    pub fn opm(&self) -> OPM_R {
        OPM_R::new(((self.bits >> 3) & 1) != 0)
    }
    ///Bit 4 - Direction Note: This bit is read only when the timer is configured in Center-aligned mode or Encoder mode.
    #[inline(always)]
    pub fn dir(&self) -> DIR_R {
        DIR_R::new(((self.bits >> 4) & 1) != 0)
    }
    ///Bits 5:6 - Center-aligned mode selection Note: Switch from edge-aligned mode to center-aligned mode as long as the counter is enabled (CEN=1) is not allowed
    #[inline(always)]
    pub fn cms(&self) -> CMS_R {
        CMS_R::new(((self.bits >> 5) & 3) as u8)
    }
    ///Bit 7 - Auto-reload preload enable
    #[inline(always)]
    pub fn arpe(&self) -> ARPE_R {
        ARPE_R::new(((self.bits >> 7) & 1) != 0)
    }
    ///Bits 8:9 - Clock division This bit-field indicates the division ratio between the timer clock (CK_INT) frequency and the dead-time and sampling clock (t<sub>DTS</sub>)used by the dead-time generators and the digital filters (ETR, TIx): Note: t<sub>DTS</sub> = 1/f<sub>DTS</sub>, t<sub>CK_INT</sub> = 1/f<sub>CK_INT</sub>.
    #[inline(always)]
    pub fn ckd(&self) -> CKD_R {
        CKD_R::new(((self.bits >> 8) & 3) as u8)
    }
    ///Bit 11 - UIF status bit remapping
    #[inline(always)]
    pub fn uifremap(&self) -> UIFREMAP_R {
        UIFREMAP_R::new(((self.bits >> 11) & 1) != 0)
    }
}
impl core::fmt::Debug for R {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIM1_CR1")
            .field("cen", &self.cen())
            .field("udis", &self.udis())
            .field("urs", &self.urs())
            .field("opm", &self.opm())
            .field("dir", &self.dir())
            .field("cms", &self.cms())
            .field("arpe", &self.arpe())
            .field("ckd", &self.ckd())
            .field("uifremap", &self.uifremap())
            .finish()
    }
}
impl W {
    ///Bit 0 - Counter enable Note: External clock, gated mode and encoder mode can work only if the CEN bit has been previously set by software. However trigger mode can set the CEN bit automatically by hardware.
    #[inline(always)]
    pub fn cen(&mut self) -> CEN_W<'_, TIM1_CR1rs> {
        CEN_W::new(self, 0)
    }
    ///Bit 1 - Update disable This bit is set and cleared by software to enable/disable UEV event generation. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller Buffered registers are then loaded with their preload values.
    #[inline(always)]
    pub fn udis(&mut self) -> UDIS_W<'_, TIM1_CR1rs> {
        UDIS_W::new(self, 1)
    }
    ///Bit 2 - Update request source This bit is set and cleared by software to select the UEV event sources. Counter overflow/underflow Setting the UG bit Update generation through the slave mode controller
    #[inline(always)]
    pub fn urs(&mut self) -> URS_W<'_, TIM1_CR1rs> {
        URS_W::new(self, 2)
    }
    ///Bit 3 - One pulse mode
    #[inline(always)]
    pub fn opm(&mut self) -> OPM_W<'_, TIM1_CR1rs> {
        OPM_W::new(self, 3)
    }
    ///Bit 4 - Direction Note: This bit is read only when the timer is configured in Center-aligned mode or Encoder mode.
    #[inline(always)]
    pub fn dir(&mut self) -> DIR_W<'_, TIM1_CR1rs> {
        DIR_W::new(self, 4)
    }
    ///Bits 5:6 - Center-aligned mode selection Note: Switch from edge-aligned mode to center-aligned mode as long as the counter is enabled (CEN=1) is not allowed
    #[inline(always)]
    pub fn cms(&mut self) -> CMS_W<'_, TIM1_CR1rs> {
        CMS_W::new(self, 5)
    }
    ///Bit 7 - Auto-reload preload enable
    #[inline(always)]
    pub fn arpe(&mut self) -> ARPE_W<'_, TIM1_CR1rs> {
        ARPE_W::new(self, 7)
    }
    ///Bits 8:9 - Clock division This bit-field indicates the division ratio between the timer clock (CK_INT) frequency and the dead-time and sampling clock (t<sub>DTS</sub>)used by the dead-time generators and the digital filters (ETR, TIx): Note: t<sub>DTS</sub> = 1/f<sub>DTS</sub>, t<sub>CK_INT</sub> = 1/f<sub>CK_INT</sub>.
    #[inline(always)]
    pub fn ckd(&mut self) -> CKD_W<'_, TIM1_CR1rs> {
        CKD_W::new(self, 8)
    }
    ///Bit 11 - UIF status bit remapping
    #[inline(always)]
    pub fn uifremap(&mut self) -> UIFREMAP_W<'_, TIM1_CR1rs> {
        UIFREMAP_W::new(self, 11)
    }
}
/**TIM1 control register 1

You can [`read`](crate::Reg::read) this register and get [`tim1_cr1::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`tim1_cr1::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).

See register [structure](https://stm32-rs.github.io/stm32-rs/STM32C092.html#TIM1:TIM1_CR1)*/
pub struct TIM1_CR1rs;
impl crate::RegisterSpec for TIM1_CR1rs {
    type Ux = u16;
}
///`read()` method returns [`tim1_cr1::R`](R) reader structure
impl crate::Readable for TIM1_CR1rs {}
///`write(|w| ..)` method takes [`tim1_cr1::W`](W) writer structure
impl crate::Writable for TIM1_CR1rs {
    type Safety = crate::Unsafe;
}
///`reset()` method sets TIM1_CR1 to value 0
impl crate::Resettable for TIM1_CR1rs {}
